### ISSUE TITLE
add more customized widget

### ISSUE THREAD

**Issue by knilink** [clearbridgesoft/form-builder#10]

**Comment by knilink** [comment]
following customized widget works:
dateTime, paymentStatus, label

Limitations:
label widget can not be assigned to an object otherwise the form engine will submit an empty object
paymentStatus widget can only be assigned to an object otherwise the form engine will raise a type error

**Comment by hnandarusdy** [comment]
paymentStatus is ok to be assigned to object, however label should be able to be plugged to anywhere, no matter if that is object / array
