### ISSUE TITLE
Editor for validation (onChange)

### ISSUE THREAD

**Issue by hnandarusdy** [clearbridgesoft/form-builder#11]
We need to have an editor so that I could make a certain form validation. For now, editor is enough and get it working first, then in the future we could enhance this to be done via UI.

**Comment by knilink** [comment]
"meteor npm install" required
a simple editor for validation is added, click on "root" or "firstName" to see the example.

Limitations:
- may have performance issue for liveValidate
- this is just quick demo for the functionality and the code needs to be refactor

**Comment by knilink** [comment]
Completed, probably need to reinstall 'react-jsonschema-form' with "https://github.com/clearbridgesoft/react-jsonschema-form/releases/download/v0.38.2/react-jsonschema-form-0.38.1.tgz" since i modified the package but didn't update the version tag.

**Comment by hnandarusdy** [comment]
validation number has some errors: 
`Uncaught TypeError: Cannot read property 'node' of undefined`
`Uncaught ReferenceError: age is not defined`

![image](https://cloud.githubusercontent.com/assets/14065403/17913799/1ce3353e-69e0-11e6-9ca4-465629a6a9ad.png)

Age is defined already, so I'm uncertain what is wrong, even in schema is defined also

> "age": {
>       "title": "Age",
>       "validate": [
>         {
>           "clause": "agee>2"
>         }
>       ],
>       "type": "integer"
>     }

**Comment by hnandarusdy** [comment]
This bug is no longer appeared, and I can validate integer value
