### ISSUE TITLE
Editor for Conditional Logic

### ISSUE THREAD

**Issue by hnandarusdy** [clearbridgesoft/form-builder#13]
As you may have been aware, we need a conditional logic to hide / show the components. 

Make an editor of conditional logic, then in the future we could enhance it using UI for basic conditional.

**Comment by knilink** [comment]
The conditional logic will only works on 'object'.
Click on an form object then the conditionl can be edited in the editor on the right side.

**Comment by hnandarusdy** [comment]
With this conditional logic, especially for hide & show, it works functionally, however is it possible to make it user friendly, and also provide a text editor to show all conditional logics for example? 

It doesn't need to be fancy, as long as it is easy to understand / view, then it is fine. 

I will create another issue to enhance the conditional logic.
