### ISSUE TITLE
add more options for radio button / select box via UI

### ISSUE THREAD

**Issue by hnandarusdy** [clearbridgesoft/form-builder#17]
From UI, we should be able to add more options for radio button and select box. 

it should generate something like this in the schema
 

> "enum": [
>         "foo",
>         "bar"
>       ],
>       "enumNames": [
>         "Foo",
>         "Bar"
>       ]

so you need two textboxes for each option
1. Label -> will generate to enumNames
2. value -> will generate to enum

It should return 1 value (in most case, it will be a string)

**Comment by knilink** [comment]
the form engine seems only support radio for boolean a customized widget needed to developed

**Comment by knilink** [comment]
just rearrange the structure of the editor so there isn't too much progress regarding to the functionality,

only support for radio at the moment

**Comment by hnandarusdy** [comment]
I just looked you have updated you previous comment, yes we are able to have radio button as a string.
here is the reference: 
https://github.com/mozilla-services/react-jsonschema-form/issues/169

**Comment by hnandarusdy** [comment]
![image](https://cloud.githubusercontent.com/assets/14065403/17992119/02ae61c6-6b88-11e6-9104-0cabea0d9373.png)


We currently use enum and enumNames on Widget & Field Configuration, we have to rename it as this is too technical-perspective. 

We only need to rename 

- [ ] enum  -> "Value"

- [ ]  enumNames -> "Label"
