### ISSUE TITLE
Setup and test form apps

### ISSUE THREAD

**Issue by knilink** [clearbridgesoft/form-builder#24]
- [x] pack up the form-builder into npm pack
- [x] setup build-app
- [x] setup client-app

**Comment by knilink** [comment]
just review this app `https://github.com/clearbridgesoft/form-builder-user-app.git` to test whether the project was setted up correctly would be fine.

limitations:
- form schemas are persist in react component state. 
- currently using the submit button in preview form to submit form schema.
- a bug may cause `Invalid root object field configuration:uiSchema order list length should match object properties length.`

**Comment by hnandarusdy** [comment]
Looks ok for first setup. 
Well done
