### ISSUE TITLE
Required field

### ISSUE THREAD

**Issue by hnandarusdy** [clearbridgesoft/form-builder#29]
Make an option of required fields in widget & field configuration. Probably something like checkbox with a text "Required"

Then if this checkbox is "ticked" then this is a mandatory field in the run time

**Comment by knilink** [comment]
**The required setting is under object editor** to specify which child fields are required, rather then a required check under each children. This is because it will bettew with the form engine since the engine use a properties list to under a object type to specify the required field.

**Comment by hnandarusdy** [comment]
Tested, but I can't test for these following fields: 
- Select box
- WYSIWYG

- Read-only for radio-button is not working also. But, this is not too common so I will create separate issue for this bug
