### ISSUE TITLE
Form Fields Bugs & Improvement

### ISSUE THREAD

**Issue by hnandarusdy** [clearbridgesoft/form-builder#37]
![image](https://cloud.githubusercontent.com/assets/14065403/18070658/acc4faf0-6e92-11e6-923b-34b7c8f7f811.png)

Add all widgets under a data type: 
for example: 
- String should have
  - Text box
  - Textarea
  - Date/Date Time
  - WYSIWYG
  - Password
  - Date
  - Datetime

(All these widgets should be similar with all widgets in 'Widget & Field Configuration')

**Comment by knilink** [comment]
the issues related to #15 and i'd like you to review it first.
i tend to make the menu like the one in jotform.
please leave a comment and assignment the issue back to me if you still think the menu need to be improve after reviewing #15 .

**Comment by hnandarusdy** [comment]
Actually, the requirement is to add a field / component under the data type. However what I see now is to have 'Quick Fields' / 'Basic Fields' / 'Custom Fields'

But, It is ok for now, we may be able to improve it later.
