### ISSUE TITLE
Editor for complex conditional logic

### ISSUE THREAD

**Issue by hnandarusdy** [clearbridgesoft/form-builder#38]
We need an editor for complex conditional logic. Currently, we only have an option to hide / show for the fields. We may have some really complex, and therefore we need this conditional editor. Make it with a large text area.

example of additional condition: 
1. to disable / enable a field
2. to update another field from value
3. to enable / disable validity

**Comment by knilink** [comment]
It done by using a custom field component.
It works but doesn't feel like is a good solution by changing the schema and formData inside the form and it may has some unknow issues.

**Comment by hnandarusdy** [comment]
in the root, we need to specify : 
```
{
  "ui:field": "fullConditional"
}
```

then, we run a script in the text editor. example:

`
function myCondition(_ref) {
  var schema = _ref.schema;
  var uiSchema = _ref.uiSchema;
  var formData = _ref.formData;
  if (formData) {
    Object.keys(schema.properties).forEach(function (name) {
      uiSchema[name] = uiSchema[name] || {};
    });	
    if (formData.textbox_1 == 'abc'){
    	formData.textbox_2 = 'hello';
    }else{
    	formData.textbox_2 = 'hihihi';
      schema.required=['textbox_2'];
    }
  }
  return { schema: schema, uiSchema: uiSchema, formData: formData };
}
`
