### ISSUE TITLE
Custom Component support plain html

### ISSUE THREAD

**Issue by knilink** [clearbridgesoft/form-builder#6]
This solution cover this issue #1

**Comment by knilink** [comment]
plain html component supported, I didn't place it into right click menu.
place following uiSchema into any form item to see the effect
`{
  "ui:field": "html",
  "ui:html": "<h1>Heading 1</h1><h2>heading 2</h2><p>content blablabla<p>"
}`

**Comment by hnandarusdy** [comment]
We need to be able to style this in the future
